advanced_features_and_security/LibraryProject/LibraryProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('bookshelf.urls'))
]

advanced_features_and_security/LibraryProject/bookshelf/urls.py
from django.urls import path
from . import views

app_name = 'bookshelf'

urlpatterns = [
    path('', views.book_list, name='book_list'),
    path('create/', views.book_create, name= 'book_create'),
    path('edit/<int:pk>/', views.book_edit, name='book_edit'),
    path('delete/<int:pk>/', views.book_delete, name='book_delete'),
    
]

advanced_features_and_security/LibraryProject/bookshelf/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

class CustomUserManager(BaseUserManager):

    def create_user(self, username, email=None, password=None, **extra_fields):
        
        if not username:
            raise ValueError('The Username field must be set')
        email = self.normalize_email(email)
        user = self. model(username = username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using= self._db)
        return user
    
    def create_superuser(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        
        return self. create_user(username, email, password, **extra_fields)

        


class CustomUser(AbstractUser):
    date_of_birth = models.DateField(null=True, blank=True)
    profile_photo = models.ImageField(upload_to='profile_photos/', null=True, blank=True)

    def __str__(self):
        return self.username

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    publication_year = models.IntegerField()

    class Meta:
        permissions = (
            ("can_view", "Can view book"),
            ("can_create", "Can create book"),
            ("can_edit", "Can edit book"),
            ("can_delete", "Can delete book"),
            
        )

advanced_features_and_security/LibraryProject/bookshelf/forms.py
from django import forms

class ExampleForm(forms.Form):
    title = forms.CharField(max_length=200)
    author = forms.CharField(max_length=100)
    publication_year = forms.IntegerField()

advanced_features_and_security/LibraryProject/bookshelf/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import permission_required
from .models import Book
from django.http import HttpResponse
from .forms import ExampleForm

@permission_required('bookshelf.can_view', raise_exception=True)
def book_list(request):
    books = Book.objects.all()
    return render(request, 'bookshelf/book_list.html', {'books': books})

@permission_required('bookshelf.can_create', raise_exception=True)
def book_create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        author = request.POST.get('author')
        publication_year = request.POST.get('publication_year')
        if title and author and publication_year:
            Book.objects.create(
                title=title,
                author=author,
                publication_year=publication_year
            )

            return redirect('book_list')
        return render(request, 'bookshelf/book_create.html')
    
@permission_required('bookshelf.can_edit', raise_exception=True)
def book_edit(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        book.title = request.POST.get('title')
        book.author = request.POST.get('author')
        book.publication_year = request.POST.get('publication_year')
        book.save()

        return redirect('book_list')
    return render(request, 'bookshelf/book_edit.html', {'book': book})

@permission_required('bookshelf.can_delete', raise_exception=True)
def book_delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method  == 'POST':
        book.delete()
        return redirect('book_list')
    return render(request, 'bookshelf/book_delete.html', {'book': book})

advanced_features_and_security/LibraryProject/bookshelf/templates/bookshelf/book_create.html
<!DOCTYPE html>
<html>
<head>
    <title>Create Book</title>
</head>
<body>
    <h1>Create a New Book</h1>
    <form method="post">
        {% csrf_token %}
        <p>Title: <input type="text" name="title" required></p>
        <p>Author: <input type="text" name="author" required></p>
        <p>Publication Year: <input type="number" name="publication_year" required></p>
        <button type="submit">Create</button>
    </form>
    <a href="{% url 'bookshelf:book_list' %}">Back to List</a>
</body>
</html>

advanced_features_and_security/LibraryProject/bookshelf/templates/bookshelf/book_delete.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Book</title>
</head>
<body>
    <h1>Delete Book</h1>
    <p>Are you sure you want to delete "{{ book.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, Delete</button>
    </form>
    <a href="{% url 'bookshelf:book_list' %}">Cancel</a>
</body>
</html>

advanced_features_and_security/LibraryProject/bookshelf/templates/bookshelf/book_edit.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Book</title>
</head>
<body>
    <h1>Edit Book</h1>
    <form method="post">
        {% csrf_token %}
        <p>Title: <input type="text" name="title" value="{{ book.title }}" required></p>
        <p>Author: <input type="text" name="author" value="{{ book.author }}" required></p>
        <p>Publication Year: <input type="number" name="publication_year" value="{{ book.publication_year }}" required></p>
        <button type="submit">Save</button>
    </form>
    <a href="{% url 'bookshelf:book_list' %}">Back to List</a>
</body>
</html>

advanced_features_and_security/LibraryProject/bookshelf/templates/bookshelf/book_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Book List</title>
</head>
<body>
    <h1>Books</h1>
    <ul>
        {% for book in books %}
            <li>{{ book.title }} by {{ book.author }} ({{ book.publication_year }})
                {% if perms.bookshelf.can_edit_book %}
                    <a href="{% url 'bookshelf:book_edit' book.pk %}">Edit</a>
                {% endif %}
                {% if perms.bookshelf.can_delete_book %}
                    <a href="{% url 'bookshelf:book_delete' book.pk %}">Delete</a>
                {% endif %}
            </li>
        {% empty %}
            <li>No books available.</li>
        {% endfor %}
    </ul>
    {% if perms.bookshelf.can_create_book %}
        <a href="{% url 'bookshelf:book_create' %}">Add New Book</a>
    {% endif %}
</body>
</html>

advanced_features_and_security/LibraryProject/bookshelf/templates/bookshelf/form_example.html
<!DOCTYPE html>
<html>
<head>
    <title>Create Book</title>
</head>
<body>
    <h1>Create a New Book</h1>
    <form method="post">
        {% csrf_token %}
        <p>Title: <input type="text" name="title" required></p>
        <p>Author: <input type="text" name="author" required></p>
        <p>Publication Year: <input type="number" name="publication_year" required></p>
        <button type="submit">Create</button>
    </form>
    <a href="{% url 'bookshelf:book_list' %}">Back to List</a>
</body>
</html>